name: Build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: 'Install Qt'
        uses: jurplel/install-qt-action@v1.0.0
      -
        name: 'Install dependencies'
        run: 'sudo apt install libgl1-mesa-dev'
      -
        name: 'Build project'
        run: 'qmake -makefile && make'
